name: nodejs-app-deploy-to-EBS

on:
   workflow_dispatch:

env:
  
  NODE_VERSION: '14.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '**/package.json'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: Zip artifact for deployment
      run: zip release.zip ./* -r
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
          name: angular-app
          path: release.zip    


  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: angular-app

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: testnodeapp
          environment_name: Testnodeapp-env
          version_label: ${{github.SHA}}
          region: us-east-2
          deployment_package: release.zip
